### ISSUE TITLE
Creating template pages [ contributor profile, meeting note,  personal effort ]

### ISSUE THREAD

**Issue by emreboun** [bounswe/bounswe2022group4#1]
**Template pages for:**

* Contiributor Profile Page for newcomer group member
* Meeting Page for weekly meetings
* Personal Effort Page for academic time tracking

**Comment by emreboun** [comment]
Following templates are added.

* Contiributor Profile Page for newcomer group member 
* Meeting Page for weekly meetings

**Comment by mbatuhan-malazgirt** [comment]
- Added [Personal Effort Template](https://github.com/bounswe/bounswe2022group4/wiki/Personal-Effort).

**Comment by emreboun** [comment]
A few things has edited at template pages. Templates are open for review.
