### ISSUE TITLE
Class Diagram: Location

### ISSUE THREAD

**Issue by oguzhantok** [bounswe/bounswe2022group4#106]
We need to add Location Class to the class diagram https://github.com/bounswe/bounswe2022group4/issues/52. All necessary functions and attributes identified in our discussions will be added.

Deadline: 15.04.2022, 11.00 (GMT+3)

**Comment by oguzhantok** [comment]
Current state is as below,

![image](https://user-images.githubusercontent.com/100778825/163603131-c6509a64-df9e-47e3-8bf1-69c60fa01191.png)

**Comment by BeratDamar** [comment]
Thanks @oguzhantok . It looks good. I added  it to [here](https://github.com/bounswe/bounswe2022group4/wiki/Class-Diagram)
