### ISSUE TITLE
Class Diagram: DatabaseHandler

### ISSUE THREAD

**Issue by sanberks** [bounswe/bounswe2022group4#107]
A database handler class is required in order to provide functioning between the database and other classes.

Deadline: 15.04.2022 - 8pm

**Comment by sanberks** [comment]
The class diagram is ready.
[Class Diagram](https://github.com/bounswe/bounswe2022group4/wiki/Class-Diagram)

**Comment by sanberks** [comment]
After the review, the issue can be closed.

**Comment by bayndrysf** [comment]
Reviewed. Thanks!
