### ISSUE TITLE
Research Git as a version control system

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#12]
Research version management systems, Git as an example of it, and GitHub as an online hosting site. 
Explain basic commands of Git.

**Comment by erdnj** [comment]
Some definitions about GitHub and basic commands of Git researched and added to [Git Research Page](https://github.com/bounswe/bounswe2022group4/wiki/Git-Research)

**Comment by bayndrysf** [comment]
Thank you for your collaboration.
