### ISSUE TITLE
Split the posts into different pages

### ISSUE THREAD

**Issue by sanberks** [bounswe/bounswe2022group4#133]
When the number of posts gets higher, showing all the posts in one page will not be suitable. Therefore, a paging can be implemented.

**Comment by sanberks** [comment]
This functionality is ready. The PR is created. After merge, this issue can be closed. @BeratDamar 
[PR](https://github.com/bounswe/bounswe2022group4/pull/134)

**Comment by yigit-can-ozkaya** [comment]
Functionality is working fine.
