### ISSUE TITLE
Practice Application - Dockerization

### ISSUE THREAD

**Issue by yigit-can-ozkaya** [bounswe/bounswe2022group4#183]
Dockerization of Practice App with MySQL DB is done. Needed review
I created different branch as Dockerization to merge later on.

**Comment by sanberks** [comment]
I have reviewed, everything seems fine. I am closing the issue, however, it would be nice if you can add the URL to the relevant branch or the PR into the issue. Thanks.

**Comment by yigit-can-ozkaya** [comment]
@sanberks  Thanks, there is the PR related to this issue : https://github.com/bounswe/bounswe2022group4/pull/224
