### ISSUE TITLE
External API

### ISSUE THREAD

**Issue by sanberks** [bounswe/bounswe2022group4#186]
Find and add an external API

**Comment by sanberks** [comment]
I used the API provided by World Health Organization on life expectancy. I also implemented a search box in the web app. The keyword sent via POST request provides a functionality of 'search-by'. The user can see the possible keywords in the dropdown list. When the keyword 'ALL' is chosen, the data of all countries in the database are displayed. Otherwise, only the data of the selected country is displayed.

This issue can be closed after review.
[Relevant PR](https://github.com/bounswe/bounswe2022group4/pull/203)

**Comment by yigit-can-ozkaya** [comment]
Reviewed.
