### ISSUE TITLE
Milestone Report II - Executive Summary

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#199]
**To do**:

- Summarize the practice project and its overall status of it. (assignee: @bayndrysf )
- Explain the basic functionality of the practice application. (assignee: @bayndrysf)
- List challenges you met as a group (assignee: @mbatuhan-malazgirt )
- List the status of deliverables (assignee: @mbatuhan-malazgirt )

-  Add the URL of the deployed application with instructions to test it
-  Add API URLs used in the application.

Deadline: 20.05.2022 16.00 (GMT+3)

**Comment by mbatuhan-malazgirt** [comment]
List challenges you met as a group (assignee: @mbatuhan-malazgirt )

List the status of deliverables (assignee: @mbatuhan-malazgirt )

These parts are done.

**Comment by mbatuhan-malazgirt** [comment]
Following part is done.

- Add API URLs used in the application.
