### ISSUE TITLE
Create Sequence Diagrams for the practice app

### ISSUE THREAD

**Issue by sanberks** [bounswe/bounswe2022group4#205]
Sequence diagrams are to be prepared for the practice app.

**Comment by sanberks** [comment]
Sequential diagrams are prepared.
[relevant link](https://lucid.app/lucidchart/53219fab-040f-4bfe-aea1-08c5c503ac34/edit?invitationId=inv_066f222c-4fbc-4212-ae4c-fcf8a552aea7)

After review of the sequential diagrams, this issue can be closed.

**Comment by sanberks** [comment]
@BeratDamar can you please review the SD's?

**Comment by BeratDamar** [comment]
Sequence diagrams  were prepared. I also reviewd and it was okey. Therefore, I will close issue.
