### ISSUE TITLE
Listing communication requirements for user requirements

### ISSUE THREAD

**Issue by BeratDamar** [bounswe/bounswe2022group4#21]
We will determine communication and messaging requirements  between users.

**Comment by eliftoklu** [comment]
We met with Berat via Zoom. We added some [Communication/Messaging Requirements](https://github.com/bounswe/bounswe2022group4/wiki/Requirements) and determined our  [Questions](https://github.com/bounswe/bounswe2022group4/wiki/Questions) about communication.
