### ISSUE TITLE
Milestone Report II, Practice Application - Class Diagram

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#212]
UML Class Diagram representing the overall structure of our practice application should be added to Milestone Report II.

**To do:"
- Review the UML Class Diagram.
- Add it into Milestone Report II.

**Comment by bayndrysf** [comment]
Done. Review needed!

**Comment by erdnj** [comment]
I reviewed Diagrams in Milestone Report II. Its OK.
