### ISSUE TITLE
Listing authentication requirements for user requirements

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#22]
I will determine authentication requirements for users.

**Comment by bayndrysf** [comment]
I checked [Meeting Notes #2](https://github.com/bounswe/bounswe2022group4/wiki/Meeting-%232,-14.03.2022) and realize that @mbatuhan-malazgirt and @umutdenizsenerr you're reviewers of this task. Can you review and close it if appropriate?

**Comment by umutdenizsenerr** [comment]
I have reviewed.
