### ISSUE TITLE
Users json decode error

### ISSUE THREAD

**Issue by sanberks** [bounswe/bounswe2022group4#220]
We need to resolve the json decode error for `/all-users/`

**Comment by sanberks** [comment]
This problem is solved. [relevant PR](https://github.com/bounswe/bounswe2022group4/pull/223)

**Comment by sanberks** [comment]
@BeratDamar  can you review and close the issue

**Comment by yigit-can-ozkaya** [comment]
Problem is non-existent now, Problem solved and reviewed.
