### ISSUE TITLE
Requirements need revision.

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#226]
[Requirements](https://github.com/bounswe/bounswe2022group4/wiki/Requirements) are in need of revision. All group members are expected to discuss the requirements, especially those of functional ones, considering the minimum requirements imposed by customers and list controversial requirements here to make the final decisions.

**Comment by BeratDamar** [comment]
After reviewing  [our requirements page](https://github.com/bounswe/bounswe2022group4/wiki/Requirements), I realized that some requirements are not correct according to fact that  a requirement should answer "what question " not "how question.". In other words, we should explain what to do  but we  should not answer how to do this task in requirements.

According to explanation above,  I think that we should change following requirements by removing "how parts" :

* 1.2.5.1 -->The system shall show the number of upvotes given to a post or comment at the lower right corner of every post or comment.
* 1.2.5.2 -->The system shall show the number of comments made to a post or comment at the lower right corner of every post or comment.

* 1.2.5.3 -->The system shall show the category of a post at the lower-left corner of every post.

**Comment by bayndrysf** [comment]
Changes in **1.1.1.1 Sign Up**:
- Some typos and ambiguities were handled.
-  *Health professionals shall be verified by a check of their national ID in the database.* :x:
   *Health professionals shall provide some additional information regarding their educational backgrounds and professional experience.* :heavy_check_mark:

**Comment by bayndrysf** [comment]
Changes in **1.1.2.1 Forum**:
- Ordering of requirements was changed, and some ambiguities were handled.

**Comment by bayndrysf** [comment]
Changes in **1.1.2.2 Profile Pages**:
- *Users shall be able to log out from their profile pages.* :x:
The logout functionality is accessible anywhere. There's no need to have this requirement.

**Comment by bayndrysf** [comment]
Changes in  **1.1.2.4 Tools**:
    *Users shall be able to access Tools from the homepage.* :x:
    *Users shall be able to pass input if required by the tool.* :x:

**Comment by bayndrysf** [comment]
All the changes was reported.
