### ISSUE TITLE
Revision on Recommendation Requirements

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#228]
As suggested at #226, I checked the [requirements](https://github.com/bounswe/bounswe2022group4/wiki/Requirements). I think there is a part about the recommendation  that can be simplified also. The reason of this simplification is functionality correction. `Following` should't be functionalized to trace of illnesses of followed ones. To set aright that two requirements should be corrected as below:
<br>
> **In Recommendations section of the System Requirements:** 

* **1.2.2.2.** *The system shall give recommendations to users:*
  * **1.2.2.2.2.** *The system shall recommend posts from followed users or health professionals.*

**to**
* **1.2.2.2.** *The system shall give recommendations to users:*
  * **1.2.2.2.2.** *The system shall recommend posts from followed health professionals.*

<br>

> **In Forum section of the System Requirements:** 

* **1.2.5.4.** *The system shall recommend posts from followed users and categories.*

**to**
* **1.2.5.4.** *The system shall recommend posts from followed health professionals and categories.*

**Comment by umutdenizsenerr** [comment]
According to the general meetings that we done and meetings we done in lab sections with our TA, i have changed the mentioned requirements.
