### ISSUE TITLE
Frontend: Create a code base for frontend team

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#231]
I need to create a base code with react.js for the frontend team in order to start the development as a team.
Steps:
1) Create a react application in suggested way.
2) Install necessary dependencies in the application.
3) Edit App.js component for routing in web application.

Deadline: 13.10.2022 23.59
Reviewer: @BeratDamar

**Comment by umutdenizsenerr** [comment]
I have created code base by using react js, installed necessary libraries and created new heka-front branch (https://github.com/bounswe/bounswe2022group4/tree/heka-front)

**Comment by BeratDamar** [comment]
Well done. It was good start for the project.
