### ISSUE TITLE
Create a navigation bar for web app

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#236]
I need to create navigation bar for our web application in order to route other pages easily.
Deadline: 24.10.2022 23.59
Reviewer: @mbatuhan-malazgirt

**Comment by umutdenizsenerr** [comment]
I have implemented navigation bar for the web application (https://github.com/bounswe/bounswe2022group4/commit/a3274bd38ceb60468a96f5c375d00289a07a60e1). Can you review @mbatuhan-malazgirt  ?

**Comment by mbatuhan-malazgirt** [comment]
We are getting a compilation error with regarding this update on our local host server. Error is the following:

Module not found: Error: Can't resolve 'react-icons/fa' in 'C:\src\components\Navbar'

Can you please fix it?

**Comment by mbatuhan-malazgirt** [comment]
I have reviewed the navigation bar. The component code is solid. The issue is closed.
