### ISSUE TITLE
Clean up stale branches and organize Git workspace

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#253]
In order for the Git workspace to be more organized, it is decided to delete unused branches from the workspace and follow a convention agreed upon when managing branches. This is the strategy to be followed:
* Each subteam shall have a development branch, namely *heka-backend*,*heka-frontend*, and *heka-mobile*.
* Subteam members may create sub-branches under their development branches specifying functionality clearly, i.e., *heka-backend/register*

**Tasks**:
- Clean up stale branches. 
- Organize a wiki-page explaining branch management strategy.

**Deadline: 31.10.2022, 22.00 (GMT+3)**

**Comment by halilsalihorhan** [comment]
For managing releases and actions, a "develepment" branch can be added

**Comment by bayndrysf** [comment]
I realized that there's a git internal limitation that doesn't allow us to create subbranches **b/c** if **b** already exists. Therefore, I suggest changing the convention to **b_/c** when creating a branch under **b** to ensure a hierarchical relationship between branches.

**Comment by bayndrysf** [comment]
Tasks completed.
