### ISSUE TITLE
Backend: Set up Swagger UI to get self-generated API documentation.

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#254]
It's really important for customers and team members to interact with APIs easily. That's why it's decided to set up Swagger UI to get self-generated API documentation. 

**Tasks:**
-  Set up Swagger UI and make it available for other subteams' members.

**Deadline: 31.10.2022, 22.00 (GMT+3)**

**Comment by bayndrysf** [comment]
Swagger integrated. See [PR#261](https://github.com/bounswe/bounswe2022group4/pull/261). However, upon further research, it was decided to migrate from *rest-framework-swagger* to its successor *drf-yasg*. So, the deadline is extended.

**Comment by bayndrysf** [comment]
Migration from *rest-framework-swagger* to *drf-yasg* was completed. 07a6db3e8ef6f52b9247706511740feb8e439745

**Comment by erdnj** [comment]
It seems like `Swagger UI` has set up and merged to `back-end` branch with `drf-yasg` migration. 
So this issue could be closed for now.
