### ISSUE TITLE
Frontend: Implement Post and PostBox Component structure for Home Page.

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#257]
Description:
According to [Frontend Meeting 2](https://github.com/bounswe/bounswe2022group4/wiki/Meeting-%232,-20.10.2022), my task is implementing post component and class structure in order to display them on the homepage of the web application.
Steps:
1) Implementing a Post component that display post written by a single user.
2) Implementing a PostBox component that displays all posts written by the users.
Deadline: 29.10.2022 23.59
Reviewer @BeratDamar

**Comment by umutdenizsenerr** [comment]
In https://github.com/bounswe/bounswe2022group4/commit/2cf41b10ba35f1cfcab88874c9deef135645ae98 and https://github.com/bounswe/bounswe2022group4/commit/e980a415b8751fa4302df286923310d3c1a0420e I have created Post component that displays single posts and also i have created PostBox component that displays all the posts that we have. Can you review @BeratDamar ?

**Comment by BeratDamar** [comment]
I reviewed implementation in related PR and then merged it. Therefore, I closed issue. Thanks @umutdenizsenerr .
