### ISSUE TITLE
Frontend: Implementation of Login Page

### ISSUE THREAD

**Issue by BeratDamar** [bounswe/bounswe2022group4#259]
**Description:** 
According to [Frontend Meeting 2](https://github.com/bounswe/bounswe2022group4/wiki/Meeting-%232,-20.10.2022), the responsibility of implementing the Login page was assigned to me.  Users and doctors can log in with thie e-mails and passwords. If they have not registered yet, there is a link to direct to registiration page. I will check if the email addresses they entered are valid. If not, the page will give a warning. If they are registered and enter their e-mail and passwords, they are directed to homepage.

**Steps to be taken:**

1.   A login page will be implemented where users and doctors can log in with their e-mails and passwords.
2.  Implementing  connection between login page and backend with provided API's.

⏰  Deadline 30.10.2022 23:59

:mag_right:  Reviewer @umutdenizsenerr

**Comment by BeratDamar** [comment]
I implemented login page where users and doctors can log in with their e-mails and passwords as described in description. As a result, step 1 was completed.  

➡️  You can look at [related pull request](https://github.com/bounswe/bounswe2022group4/pull/265).

**Comment by BeratDamar** [comment]
I redesign login page to be more user friendly  and I connected login page to backend API.  Now, I added required error message  according to responses that I got from API. 

➡️ You can look at [related PR](https://github.com/bounswe/bounswe2022group4/pull/274).

**Comment by BeratDamar** [comment]
@umutdenizsenerr 
 Can you review login page ? If it seems okey, you can close this issue. Thanks !

**Comment by umutdenizsenerr** [comment]
I have reviewed the PR and everything is okey. Since PR is merged, I am closing the issue.
