### ISSUE TITLE
Frontend: Render the Posts in the HomePage

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#260]
Description:
According to [Frontend Meeting 2](https://github.com/bounswe/bounswe2022group4/wiki/Meeting-%232,-20.10.2022), my task is rendering the posts that are written by the users in the home page.
Steps:

1) Render PostBox component in the home page by implementing necessary import statements.
2) Prepare dummy data in order to show some posts for the milestone.
Deadline: 29.10.2022 23.59
Reviewer @yigit-can-ozkaya

**Comment by umutdenizsenerr** [comment]
I have rendered the posts in the homepage in https://github.com/bounswe/bounswe2022group4/commit/dc4439ea02b40eceab1b492e84c0e4673dd237ce. Can you review @yigit-can-ozkaya ?

**Comment by yigit-can-ozkaya** [comment]
@umutdenizsenerr That looks perfect!
