### ISSUE TITLE
Frontend: Change dummy data for real case scenarios in PostBox Component

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#264]
I have created some dummy posts like user: user1, content: post1 i need to change them for the real case scenarios like user: umutdenizsenerr, content: I have headache for two days at left of my head and it is getting worse day by day.

Deadline: 29.10.2022
Reviewer: @yigit-can-ozkaya

**Comment by umutdenizsenerr** [comment]
I have changed dummy posts to the real case scenarios in https://github.com/bounswe/bounswe2022group4/commit/cc5f7d63d36c89df282767a05f93e99a11b41efb. Can you review @yigit-can-ozkaya ?

**Comment by yigit-can-ozkaya** [comment]
@umutdenizsenerr yes, it works great!
