### ISSUE TITLE
Frontend: Unit Tests for Log in Page

### ISSUE THREAD

**Issue by BeratDamar** [bounswe/bounswe2022group4#284]
**Description:**

I completed sign in page. Firstly, I implemented log in page without backend connection using e-mail and password fields #259 . Secondly, I made its connection with backend API's #282 . After these steps,  I will be writing unit test for the login page of our application.

Since I have never written unit test with React before, I have to research about how to write unit test in React. After research step, I  I will be writing the unit tests.

**Steps to be taken:**

1.  Research on possible unit testing methods in React
2.  Choose the best one for our project.
3.  Designing test scenarios.
4.  Impelement tests for designed scenarious 
5.  Compare results with expected results.

⏰  Deadline: 31.10.2022 , 23:59

Reviewer : @umutdenizsenerr

**Comment by BeratDamar** [comment]
I researched testing methodologies in React. I chose optimal one for our project. Seconly, I created a base for testing in our project repository adding required files and folders etc. Secondly, I designed test scenarios and then implemented them. All tests are passed successfully.  Other team members of front-end can use  that base to test their codes.

**Comment by BeratDamar** [comment]
@umutdenizsenerr If everthins seems okey, you can close issue.

**Comment by umutdenizsenerr** [comment]
I have reviewed the PR and everything is okey. Since PR is merged, I am closing the issue.
