### ISSUE TITLE
Frontend: Unit Tests for Home Page

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#285]
Description: 
I have finished implementation of the HomePage. I first implement a single post component then i implement a postbox component for rendering the all posts. Then i render postbox component in homepage in ui friendly way. Now i need to write unit test cases for the home page by using react testing library.

Steps:
1) Research on React Testing Library and unit test cases.
2) Prepare test case scenarios.
3) Implement these scenarios in web application.

Reviewer: @BeratDamar

**Comment by BeratDamar** [comment]
I review related PR. Therefore, I will close the issue since it seems okey.
