### ISSUE TITLE
Commit message format

### ISSUE THREAD

**Issue by MercerFrey** [bounswe/bounswe2022group4#292]
Commit messages should be in the same format. Otherwise, they look unorganized and unprofessional. I think the following is a good format to use as a team. https://cbea.ms/git-commit/

**Comment by erdnj** [comment]
@MercerFrey, thanks in advance.
Commit messages are essential as mentioned by you and the article.

I want to also supply a commit format for team with some quick rules which could be keep in mind easily.

- Rule 1: Commit frequently, not after a big changes. Which provide coverage of the message on change.
- Rule2: Mention about the altered classes or structures then changed/added/removed functionalities. 

 As an example:

`On PageHandler, showing suggested posts functionality added.`

**Comment by MercerFrey** [comment]
I think we are all on the same page about the commit messages. Closing
