### ISSUE TITLE
Update the Personal Wiki Page

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#304]
Description:
I need to update my personal wiki page because it is outdated. I will add new fields and update old informations

Deadline: 01.11.2022 10.00
Reviewer: @yigit-can-ozkaya

**Comment by umutdenizsenerr** [comment]
I have updated my personal wiki page. Can you review @yigit-can-ozkaya ?

**Comment by yigit-can-ozkaya** [comment]
@umutdenizsenerr these are looking good!
