### ISSUE TITLE
Mobile Team Meeting Notes Have Forgotten

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#326]
⚠️  We made 3 mobile team meeting but non of them are documented . 
* I decided to fill them as  I remembered.

**Comment by erdnj** [comment]
Below Meeting Notes Has Filled as remembered:
* [Mobile Team Meeting #1](https://github.com/bounswe/bounswe2022group4/wiki/Mobile-Team-Meeting-%231)
* [Mobile Team Meeting #2](https://github.com/bounswe/bounswe2022group4/wiki/Mobile-Team-Meeting-%232)
* [Mobile Team Meeting #3](https://github.com/bounswe/bounswe2022group4/wiki/Mobile-Team-Meeting-%233)

**Comment by erdnj** [comment]
@halilsalihorhan or @FatihAkgoz could you double-check and close this issue properly ?

**Comment by halilsalihorhan** [comment]
checked.
