### ISSUE TITLE
Milestone 1: Evaluation of tools and processes used to manage team project

### ISSUE THREAD

**Issue by BeratDamar** [bounswe/bounswe2022group4#332]
**Description:**
I will evaluate tools and processes used to manage team project. 

**Steps to be taken:**
* I will make a list of tools used during project development for Milestone 1.  
* I will evaluate them considering our project.

⏰ Deadline: 04.11.2022 22:00

🔎 Reviewer: @erdnj

**Comment by erdnj** [comment]
I added `Android Studio` under Evaluation of Tools.
And merged in #334 . 
After the completion of tasks I will review all.

**Comment by BeratDamar** [comment]
I evaluated folowing tools:
*  `Discord`   
* `Github` 
*  `React` 
*  `Python Django Rest Framework` 
* `Docker` 
*   `Visual Studio Code`
* `Lucidchart` 
* `Docker`
 
➡️ For more information, you can look at [related commit](https://github.com/bounswe/bounswe2022group4/commit/e593ae57560a68ecbe4aa8f8ee613a9681c49c97)

**Comment by BeratDamar** [comment]
@erdnj If everthing is okey, you can close issue. Thank for your contribution.

**Comment by erdnj** [comment]
I reviewed the work which have done. It seems quite well. Good work @BeratDamar.
I close this issue.
