### ISSUE TITLE
Preparing a Scenario and Mock-up for  a Regular User

### ISSUE THREAD

**Issue by BeratDamar** [bounswe/bounswe2022group4#34]
We need to prepare a scenario and mockup for a regular user who wants to search for a physical problem on the application as a subgroup of three.

Subgroup Members: @BeratDamar, @eliftoklu, @bayndrysf
Deadline: Wednesday, 23 March 2022, 12:00 AM

**Comment by bayndrysf** [comment]
Mockup design for Scenario I updated. [see](https://github.com/bounswe/bounswe2022group4/wiki/Mockups)

**Comment by BeratDamar** [comment]
We completed Mockups and Scenario I and review is completed.
