### ISSUE TITLE
Preparing a Scenario and Mockup for a Regular User

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#39]
We need to prepare a scenario and mockup for a regular user who wants to search for a physical problem on the application as a subgroup of three.

Subgroup Members: @BeratDamar, @eliftoklu, @bayndrysf 
Deadline: Wednesday, 23 March 2022, 12:00 AM

**Comment by erdnj** [comment]
I review regular user scenario and I think these requirements should also be added under acceptance criteria.
* 1.1.2.1.5 A User shall be able to read a post shared by another user.
* 1.1.2.1.6 A User should be able to rate a comment out of 10.

**Comment by bayndrysf** [comment]
The issue about creating a scenario for a regular user was already created by another team member @BeratDamar. Here is the [related issue](https://github.com/bounswe/bounswe2022group4/issues/34) .Closed due to this inconvenience.
