### ISSUE TITLE
Customize the “issues” by specializing them.

### ISSUE THREAD

**Issue by mbatuhan-malazgirt** [bounswe/bounswe2022group4#4]
### Description:
We have built-in labels however we need to find and add other issue labels for our future work.

### To Do:

- Please research creative labels and add them to our label list. 
- Elif Toklu, Umut Deniz Şener and Miraç Batuhan Malazgirt were assigned for this task in our weekly meeting. However, any team member who made an addition can assign himself/herself.
- After making additions, we can comment under this issue to define which labels are added.

**Comment by mbatuhan-malazgirt** [comment]
Built-in labels were edited to the form of "Category - LabelName".

**Comment by mbatuhan-malazgirt** [comment]
Priority High, Medium, Low labels were added.

**Comment by mbatuhan-malazgirt** [comment]
I edited built-in labels to the form of "Category - LabelName".

**Comment by mbatuhan-malazgirt** [comment]
Priority High, Medium, Low labels were added.

**Comment by mbatuhan-malazgirt** [comment]
Category - Research, Priority: Severe and eight "Status: LabelName" labels were added.

**Comment by umutdenizsenerr** [comment]
Difficulty Easy, Medium, Hard labels were added.

**Comment by umutdenizsenerr** [comment]
Language labels were added.

**Comment by mbatuhan-malazgirt** [comment]
We currently have 40 labels. It is enough number, and variety for our issues. Closed.
