### ISSUE TITLE
Management: Annotations For Milestone 2

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#488]
Description:

I will prepare the annotation part of the group report. 

Steps:

1) Describe the status of annotations in our project
2) Provide the plans for implementing all functionalities associated with annotations

Reviewer: @BeratDamar 
Deadline: 09.12.2022 23.59

**Comment by umutdenizsenerr** [comment]
I have prepared the annotation part of the group report and integrate it to group report.

**Comment by BeratDamar** [comment]
I reviewed your documentation. Everthing seems good and well explained. Thanks for your contribution !
