### ISSUE TITLE
Management:  Documenting Progress according to Requirements for Milestone 2 

### ISSUE THREAD

**Issue by BeratDamar** [bounswe/bounswe2022group4#494]
### Description:
We are assigned to document our progress according to requirments for Milestone 2. In other words, we determine which requirements are satisfied and which requirements will be provided for the next Milestone.

### Steps to be taken:

1.  We will review our web and mobil application again.
2. We will review our requirements.
3. By comparing our requirements and applications,  we will determine their progress.
4.  We will document the progress according to requirements.

### ⏰  Deadline:
* 09.12.2022 15:30

### 🔎   Reviewer
* @umutdenizsenerr

**Comment by BeratDamar** [comment]
@MercerFrey  I reviewed all requirements and determined progress for them. I also documented on [Milestone 2 Report](https://github.com/bounswe/bounswe2022group4/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_2/Customer_Milestone_2.md). I thought that there are some conflicts between our application and our requirements for sign up .I believe that our application design seems more logical in terms of privacy and content of our application. Can you check them ? 

I also could not determine exact progress of some requirements especially  for the  backend related requirements  
Can you review them ?

**Comment by MercerFrey** [comment]
Yes, i will review them now. Good job!

**Comment by MercerFrey** [comment]
I finished reviewing the requirements. We need to arrange a meeting and talk about sign-up process for the health experts and admins.

**Comment by MercerFrey** [comment]
This issue is done. Closing.
