### ISSUE TITLE
Constructing a Class Diagram 

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#52]
We need to prepare a class diagram that describes the project via classes, their attributes&methods, and the relationships between them. It should include the entities listed below.

- [x] User
1. Regular User
2. Health Professional
3. Admin

- [x] Post
- [x] Tag
- [x] Comment
- [x] Report
- [x] Chat
- [x] Message 
- [x] Category
- [x] Chatbot
- [x] NotificationHandler
-  [x] SearchHandler
 - [x] DatabaseHandler

**This list is subject to change upon further analysis.**

All the instance-level and class-level relationships should be clear and consistent for the sake of future work. Group members are expected to track the overall progress here and refer to this issue in other issues if required.

Deadline: 23:00
Monday, April 14, 2022 (GMT+3)

**Comment by bayndrysf** [comment]
*User* classes are added accordingly. [issue#54](https://github.com/bounswe/bounswe2022group4/issues/54) It's in review process.

**Comment by mbatuhan-malazgirt** [comment]
Comment entity is added according to given requirements.
[Related Issue](https://github.com/bounswe/bounswe2022group4/issues/70#issuecomment-1099142917)

**Comment by oguzhantok** [comment]
Location class is added according to needs, [#106](https://github.com/bounswe/bounswe2022group4/issues/106)

**Comment by sanberks** [comment]
DatabaseHandler class is ready. #107
