### ISSUE TITLE
Class Diagram: User Types

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#54]
We need to add  *User* entity which includes *Guest*, *Regular User*, *Health Professional*, and *Admin* entities as subclasses to Class Diagram. All the required functionalities and attributes determined in our discussions are to be added to the relevant (sub)classes.

Deadline: 12.04.2022, 11.00 (GMT+3)

**Comment by bayndrysf** [comment]
They all are drawn up accordingly. *User* is designed as an abstract class. *Guest* and *RegisteredUser* inherits from *User*. *RegularUser*, *HealthProfessional*, and *Admin* inherit from *RegisteredUser*. Required functions and attributes are also added. 
Needs to be reviewed.

**Comment by oguzhantok** [comment]
Class Diagram for User Types is reviewed, it looks legitimate.
