### ISSUE TITLE
Implementation of Sequence Diagrams

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#55]
We must to prepare a sequence diagrams according to Class and User Diagrams.

----------------
* Report a Post 
- [x] Assigned
- [x] Done
----------------
* Create a Discussion Thread
- [x] Assigned
- [x] Done
----------------
* Delete Post
- [x] Assigned
- [x] Done
----------------
* Upvote a Post
- [x] Assigned
- [x] Done
----------------
 * Comment
- [x] Assigned
- [x] Done
----------------
* Follow a Category
- [x] Assigned
- [x] Done
----------------
* Change the category of a post
- [x] Assigned
- [x] Done
----------------
* Send messages to another user
- [x] Assigned
- [x] Done
----------------
* Follow a Health Professional
- [x] Assigned
- [x] Done
----------------
* Block a user
- [x] Assigned
- [x] Done
----------------
* Unblock a user
- [x] Assigned
- [x] Done
----------------
* Edit Profile Information
- [x] Assigned
- [x] Done
----------------
* Forget Password
- [x] Assigned
- [x] Done
----------------
* Login 
- [x] Assigned
- [x] Done
----------------
* Register as Regular User 
- [x] Assigned
- [x] Done
----------------
* Register as Doctor
- [x] Assigned
- [x] Done
----------------
* Delete Comments (Admin)
- [x] Assigned
- [x] Done
----------------
* Ban User (Admin) 
- [x] Assigned
- [x] Done
----------------
### Important Note ###
* If you notice some new sequence diagrams to be implement, **comment under issue**. Those will be added after review.
* I select some needed sequence diagrams which should be implemented from my aspect.
* Tick the assigned box of related task when you gonna do the job, not occupy the tasks for a long times. Remind that assigned box are not reservation boxes ! Assign it and do it.

Deadline: 22:00
April 15, 2022 (GMT+3)

**Comment by oguzhantok** [comment]
I assigned Follow a User, Unfollow a User, Block a User and Unblock a User to myself.

**Comment by erdnj** [comment]
I assigned Delete Post, Upvote a Post, Comment, Follow a Category.

**Comment by yigit-can-ozkaya** [comment]
I assigned
 *Register as Doctor
 *Register as Regular User
 *Login
 *Forget Password

**Comment by eliftoklu** [comment]
I assigned
* Change the category of a post
* Send messages to another user
 to myself

**Comment by sanberks** [comment]
I assigned:

1. Delete Comments (Admin)
2. Ban User (Admin)
3. Edit Profile Information

**Comment by umutdenizsenerr** [comment]
I assigned:

* Create a Discussion Thread

**Comment by mbatuhan-malazgirt** [comment]
I assigned 

- Approve doctor's registiration request (Admin).

**Comment by bayndrysf** [comment]
Delete a Comment assigned by @bayndrysf.

**Comment by BeratDamar** [comment]
All diagrams are completed and send to me.  Thanks guys.

@yigit-can-ozkaya  and @oguzhantok  will add diagrams to [here](https://github.com/bounswe/bounswe2022group4/wiki/Sequence-Diagrams)
