### ISSUE TITLE
Frontend: User Sign-up Password Confirm

### ISSUE THREAD

**Issue by mbatuhan-malazgirt** [bounswe/bounswe2022group4#578]
This task is later assigned to the @BeratDamar therefore the issue is closed.

**Comment by BeratDamar** [comment]
Dear @mbatuhan-malazgirt , 

This task is assigned to me according to last problem solution section . I am responsible for registration and sign-in process including email verificaiton ,KVVK clarification text  and improvement of registration.  I have already started to implement them 

Thank you for your understanding
