### ISSUE TITLE
Create "Follow a Health Professional" Sequence Diagram 

### ISSUE THREAD

**Issue by oguzhantok** [bounswe/bounswe2022group4#58]
Sequence Diagram for "Follow a Health Professional" functionality will be created according to Class and User Diagrams.

**Comment by BeratDamar** [comment]
I design fallowing sequence diagram.

![sequence](https://user-images.githubusercontent.com/74484731/163587093-7650d8ec-cb8e-4a89-b8e2-1b987337e665.PNG)
