### ISSUE TITLE
Create "Block a User" Sequence Diagram

### ISSUE THREAD

**Issue by oguzhantok** [bounswe/bounswe2022group4#59]
Sequence Diagram for "Block a User" functionality will be created according to Class and User Diagrams.

**Comment by oguzhantok** [comment]
Diagram has done as below,
![image](https://user-images.githubusercontent.com/100778825/163421310-2c0e8e67-70ac-436f-b1f0-1ad8e90974ef.png)

**Comment by bayndrysf** [comment]
Reviewed. No need to further revision. Thank you!
