### ISSUE TITLE
Create "Unblock a User" Sequence Diagram

### ISSUE THREAD

**Issue by oguzhantok** [bounswe/bounswe2022group4#60]
Sequence Diagram for "Unblock a User" functionality will be created according to Class and User Diagrams.

**Comment by oguzhantok** [comment]
Diagram has done as below,
![image](https://user-images.githubusercontent.com/100778825/163421712-ebc99bea-7de5-4293-aad8-3b67afb7b9fe.png)

**Comment by erdnj** [comment]
Reviewed. It is OK.
