### ISSUE TITLE
Class Diagram: Post

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#61]
We need to add **Post** entity to the class diagram [issue52](https://github.com/bounswe/bounswe2022group4/issues/52). All the required functionalities and attributes determined in our discussions are to be added. Its relationships with **User**, **Category**, and **Comment** should meet the requirements.

Deadline: 15.04.2022, 11.00 (GMT+3)

**Comment by erdnj** [comment]
Contributed new functions according to sequence diagram needs.

**Comment by BeratDamar** [comment]
I finished post class diagram. You can see final version [here](https://lucid.app/lucidchart/41b82bbb-f730-4157-bfd4-3c2a7af9bb3d/edit?invitationId=inv_134804c1-1fe4-44cc-a0ab-6ff7bda52ea5&page=HWEp-vi-RSFO#)

**Comment by bayndrysf** [comment]
Reviewed. No need to further revision considering our requirements. Thank you! @BeratDamar
