### ISSUE TITLE
Research on Use-case, Class and  Sequence Diagram

### ISSUE THREAD

**Issue by BeratDamar** [bounswe/bounswe2022group4#63]
* I will research for use-case,class and swequence diagram. After that, I will look at diagram examples that are done in previous semester. 
* I will update my use-case , Class and sequence diagram according to these researches.

Deadline: 13.04.2022 ,23:59

**Comment by mbatuhan-malazgirt** [comment]
I researched previous year's diagrams and updated my assigned use case - class and sequence diagrams accordingly.

**Comment by BeratDamar** [comment]
I researched  previous year's diagrams and updated my Use Case, Class and Sequence Diagrams.

**Comment by BeratDamar** [comment]
I reviewed Diagrams done by @umutdenizsenerr  and @mbatuhan-malazgirt .Therefore, I closed issue. Thanks!
