### ISSUE TITLE
PRESENTATION: Create Scenarios For Final Customer Presentation

### ISSUE THREAD

**Issue by BeratDamar** [bounswe/bounswe2022group4#636]
### Description:
We will meet with @MercerFrey in BM4 and we will create realistic scenarios for final customer presentation. 
* We will decide to which functionalities we will present and how to present them.
* We will prepare a demo and document it to use during presentation. 
*  We will also test projector and computers that will be used during presentation to encounter a problem like first Milestone.
*  We have started to create post and comments to fill our system as much as possible. We will continue to use our functionalities with a lot of users. (Customer wanted to create  different realistic post and comments)

### ⏰  Deadline:
* 27.12.2022 13:00

**Comment by MercerFrey** [comment]
We created the scenario and realistic posts. Presentation is done. There were no problems. Closing.
