### ISSUE TITLE
Sequence Diagram: Delete Post

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#64]
Delete Post Sequence Diagram has done.
It is open to comment and revisions.

_Assigned from https://github.com/bounswe/bounswe2022group4/issues/55#issuecomment-1097194940_

**Comment by erdnj** [comment]
* Diagram has done as below
 
![delete](https://user-images.githubusercontent.com/69752782/163237113-7b0e70d8-c82d-4280-a5d1-2d0d39663cde.png)

**Comment by yigit-can-ozkaya** [comment]
Reviewed

**Comment by yigit-can-ozkaya** [comment]
This diagramwas reviewed again, added to GitHub and report
