### ISSUE TITLE
Sequence Diagram: Upvote A Post

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#65]
Upvote a Post Sequence Diagram has done.
It is open to comment and revisions.

_Assigned from https://github.com/bounswe/bounswe2022group4/issues/55#issuecomment-1097194940_

**Comment by erdnj** [comment]
* Diagram has done as below
 
![upvote](https://user-images.githubusercontent.com/69752782/163237053-8ddeab6e-0bd3-4af2-899e-0bf3ceeeb1d2.png)

**Comment by yigit-can-ozkaya** [comment]
Reviewed

**Comment by BeratDamar** [comment]
It seems okey.I will close issue now. Thanks
