### ISSUE TITLE
Sequence Diagram: Comment

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#66]
Comment Sequence Diagram has done.
It is open to comment and revisions.

_Assigned from https://github.com/bounswe/bounswe2022group4/issues/55#issuecomment-1097194940_

**Comment by erdnj** [comment]
* Diagram has done as below
 
![Comment](https://user-images.githubusercontent.com/69752782/163236960-bc0a62ca-923c-44d5-9b39-6e214bdc2713.png)

**Comment by BeratDamar** [comment]
I reviewed diagram. It is okey. It confirms requirements and class diagrams. Thanks !

**Comment by erdnj** [comment]
* Diagram has updated
![commment](https://user-images.githubusercontent.com/69752782/163610556-7f8fb117-4374-45f1-99fd-ec4fc76f5b13.png)

**Comment by sanberks** [comment]
The review is done, the diagram is appropriate.
