### ISSUE TITLE
Sequence Diagram: Follow a Category

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#67]
Follow a Category Sequence Diagram has done.
It is open to comment and revisions.

_Assigned from https://github.com/bounswe/bounswe2022group4/issues/55#issuecomment-1097194940_

**Comment by erdnj** [comment]
* Diagram has done as below
 
![follow](https://user-images.githubusercontent.com/69752782/163236505-29052f28-291b-4032-8444-785fb4225c01.png)

**Comment by BeratDamar** [comment]
I reviewed last version of the diagram. Everything seems okey. Thanks  !_**@erdnj**_ . 

You can see  diagram [here](https://github.com/bounswe/bounswe2022group4/wiki/Sequence-Diagrams)
