### ISSUE TITLE
Class Diagram: Report

### ISSUE THREAD

**Issue by erdnj** [bounswe/bounswe2022group4#68]
We need to Report class to sending them and taking them from list will facilitate the works.
Requirements are report-sender information and reported post or comment's info.

**Comment by erdnj** [comment]
* Diagram has done as below
 
![Report](https://user-images.githubusercontent.com/69752782/163236827-e89b347b-1269-4252-a341-1700219637a8.png)

**Comment by erdnj** [comment]
* Current state is as below

![image-6](https://user-images.githubusercontent.com/69752782/163238029-5d76e7d2-46cb-4597-abd7-e987c18c725d.png)

**Comment by BeratDamar** [comment]
I review all class diagram. There is no contradiction with other classes. It seems okey. Therefore, I will close issue. 

Thanks @erdnj . 👍
