### ISSUE TITLE
Class Diagram: Comment

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#70]
We need to add **Comment** entity to the class diagram [issue52](https://github.com/bounswe/bounswe2022group4/issues/52). All the required functionalities and attributes determined in our discussions are to be added. Its relationships with **User** and **Post** should meet the requirements.

- **Post** instance has zero or more **Comment**s.
- **Comment** instance has zero or more **Comment**s.

Deadline: 15.04.2022, 11.00 (GMT+3)

**Comment by mbatuhan-malazgirt** [comment]
Comment entity is added to the class diagram according to given requirements.
