### ISSUE TITLE
Use Case Diagram: Determine guest use cases

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#72]
Determining the guest use cases

**Comment by sanberks** [comment]
This is completed.

[Use Case Diagram](https://github.com/bounswe/bounswe2022group4/wiki/Use-Case-Diagram)

**Comment by sanberks** [comment]
After review, the issue can be closed.

**Comment by oguzhantok** [comment]
i reviewed this issue, it looks legitimate!
