### ISSUE TITLE
Use Case Diagram: Draw the diagram with lucidchart

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#74]
Drawing the use case diagram with lucid chart

**Comment by umutdenizsenerr** [comment]
Diagram has done below.
 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/74681908/163249616-06705c1e-2082-40fa-af05-b143c850f6fc.png">

**Comment by mbatuhan-malazgirt** [comment]
I have reviewed the diagram and confirmed it is complete. Issue can be closed.
