### ISSUE TITLE
Update the requirements

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#75]
**To Do:** Requirements must be updated according to [ customer meeting feedback.](https://github.com/bounswe/bounswe2022group4/wiki/Costumer-Meeting-2)

**Deadline: ** 15.04.2022 10.00 P.M

**Comment by mbatuhan-malazgirt** [comment]
The issue is edited and more specified. Sort, Filter and Search sections of the requirements will be more detailed after the update.

**Comment by mbatuhan-malazgirt** [comment]
The update is done.
