### ISSUE TITLE
Class Diagram: Category, Tag

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#78]
We need to add **Category** and **Tag** entity to the class diagram [issue52](https://github.com/bounswe/bounswe2022group4/issues/52). All the required functionalities and attributes determined in our discussions are to be added. Its relationships with **Post** should meet the requirements:

- **Category** instance has zero or more **Post**s.
- **Post** instance has exactly one **Tag**.
- **Tag** denotes the type of **Post**. **Post** is either an article shared by **HealthProfessional** or a medical experience shared by **RegisteredUser**. 

Deadline: 15.04.2022, 11.00 (GMT+3)

**Comment by eliftoklu** [comment]
Category and tag entities are added to class diagram including requirements specified in this issue.

**Comment by sanberks** [comment]
I have reviewed the specified class diagram entities. Tag and Category classes are complete, however, Post class needs revision.  shared_location, photo_src and video are the fields requiring the revision. 

Suggested updates are: 
      shared_location: String
      photo_src: String
      replace the field video with video_src: String
      resolve video? photo? line in the diagram

After the changes are done, the issue can be closed after a final review.

**Comment by bayndrysf** [comment]
Reviewed. No need to further revision.
