### ISSUE TITLE
Researching on W3C Web Annotation Data Model and W3C standards

### ISSUE THREAD

**Issue by BeratDamar** [bounswe/bounswe2022group4#80]
* We will  research about W3C Web Annotation Data Model and W3C standards.
* We will document under [Publishments](https://github.com/bounswe/bounswe2022group4/wiki)

Deadline 14.04.2022, 17:00

**Comment by eliftoklu** [comment]
[Research](https://github.com/bounswe/bounswe2022group4/wiki/W3C-Web-Annotation-Data-Model)  is done, wiki page is created and added to [Publishments](https://github.com/bounswe/bounswe2022group4/wiki)

**Comment by BeratDamar** [comment]
We completed research and documentation.
