### ISSUE TITLE
Class Diagram: SearchHandler, NotificationHandler

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#82]
We need to add **SearchHandler** and **NotificationanHandler**  to the class diagram [(issue52)](https://github.com/bounswe/bounswe2022group4/issues/52). All the required functions and attributes determined in our discussions are to be added. Its relationships with User should meet the requirements:

-  **User** instance has exactly one **SearchHandler**.
-  **User** instance has exactly one **NotificationHandler**.

Deadline: 15.04.2022, 11.00 (GMT+3)

**Comment by erdnj** [comment]
Search Handler completed with its three helper classes.
* HealthProfessional_Search
* Semantic_Search
* Advanced_Search

![image-8](https://user-images.githubusercontent.com/69752782/163620768-f4b6625c-c00f-4910-893b-be1db86819ca.png)

**Comment by erdnj** [comment]
* Notification Handler also done.

![image-9](https://user-images.githubusercontent.com/69752782/163621714-2df64cf0-5fa0-4d29-b938-028965c0b7b4.png)

**Comment by sanberks** [comment]
Thr issue is reviewed. The classes seem appropriate.
