### ISSUE TITLE
Milestone Report 1: Preparing Responsibility Assignment Matrix

### ISSUE THREAD

**Issue by mbatuhan-malazgirt** [bounswe/bounswe2022group4#84]
**To Do:** Responsibility Assignment Matrix has to be prepared for the Milestone 1 Report.

**Deadline:** 14.04.2022 10.00 P.M

**Comment by mbatuhan-malazgirt** [comment]
Responsibility Assignment Matrix is prepared. RAM can be seen from the following link:
https://docs.google.com/spreadsheets/d/1N1ijq_IBTI3aSS6LgjJhQSAvQ3OODeSeov-KazLstU0/edit#gid=0

@BeratDamar  can you review the link and close the issue if there is no update needed?

**Comment by BeratDamar** [comment]
Everything seems okey. I reviewed all entities. Thanks guys. Therefore, I will close issue.
