### ISSUE TITLE
Preparing up to date wiki pages, Glossary and Requirements for Milestone I

### ISSUE THREAD

**Issue by umutdenizsenerr** [bounswe/bounswe2022group4#87]
Preparing up to date wiki pages and Requirements for Milestone I

**Comment by BeratDamar** [comment]
I reviewed requirements. I added  some requirements that are not specified but used in sequence diagrams and class diagrams.
* I added all requirements under 1.2.3 Chatbot
* I added all requirements under messaging 1.1.2.3.
* I updated sig-up requirements for doctors.(1.1.1.1.9 and 1.1.1.1.11).
* I add  requirements under Searching that are not included but used in Diagrams.

You can see other updates in [here](https://github.com/bounswe/bounswe2022group4/wiki/Requirements/_history).

**Comment by umutdenizsenerr** [comment]
I reviewed glossary and added the words 

* chatbot
* follow
* unfollow
* discussion thread
* notification
* username
* password
* ban
* report
* homepage
* search
* chat
* upvote
* validate
* sort
* filter

**Comment by BeratDamar** [comment]
Hey @mbatuhan-malazgirt ! You can close issue after reviewing updates. Thanks !

**Comment by mbatuhan-malazgirt** [comment]
I have reviewed all the updates, they all look complete issue can be closed.
