### ISSUE TITLE
Discover some repositories on GitHub

### ISSUE THREAD

**Issue by sanberks** [bounswe/bounswe2022group4#9]
Find some repos on GitHub and document why you like them.

**Comment by sanberks** [comment]
I completed my part on this issue. If everybody did so, can we close the issue?

**Comment by oguzhantok** [comment]
I also completed my part.

**Comment by mbatuhan-malazgirt** [comment]
I added one repository to the research.

**Comment by BeratDamar** [comment]
I also completed my part.
