### ISSUE TITLE
Sequence Diagram Edit Profile Information

### ISSUE THREAD

**Issue by sanberks** [bounswe/bounswe2022group4#92]
I assigned Edit Profile Information sequence diagram.

_Assigned by @sanberks in https://github.com/bounswe/bounswe2022group4/issues/55#issuecomment-1098368049_

**Comment by sanberks** [comment]
The sequence diagram is completed.

**Comment by sanberks** [comment]
![Sequence diagram - Edit Profile Information](https://user-images.githubusercontent.com/67700869/163502723-10e97da2-cbba-4f97-9c8b-81bd4aede528.png)

**Comment by mbatuhan-malazgirt** [comment]
I have reviewed this sequence diagram. It is complete and solid. The issue can be closed.
