### ISSUE TITLE
Sequence Diagram Register as Regular User

### ISSUE THREAD

**Issue by sanberks** [bounswe/bounswe2022group4#93]
I assigned Register as Regular User sequence diagram.

_assigned by @sanberks in https://github.com/bounswe/bounswe2022group4/issues/55#issuecomment-1098368049_

**Comment by sanberks** [comment]
The diagram is completed.
![Sequence diagram - Register as RegUs](https://user-images.githubusercontent.com/67700869/163503147-8ebafb25-a36a-4104-9230-2f43fe916396.png)

**Comment by mbatuhan-malazgirt** [comment]
I have reviewed this sequence diagram. It is complete and solid. The issue can be closed.
