### ISSUE TITLE
Sequence Diagram Register as Doctor

### ISSUE THREAD

**Issue by sanberks** [bounswe/bounswe2022group4#94]
I assigned Register as Doctor sequence diagram.

_Assigned by @sanberks in https://github.com/bounswe/bounswe2022group4/issues/55#issuecomment-1098368049_

**Comment by sanberks** [comment]
![Sequence diagram - RegAsDoc](https://user-images.githubusercontent.com/67700869/163503223-6ca78aef-1422-4b3a-9e9c-e92e640daf5d.png)

**Comment by mbatuhan-malazgirt** [comment]
I have reviewed this sequence diagram. It is complete and solid. The issue can be closed.
