### ISSUE TITLE
Sequence Diagram: Delete a Comment

### ISSUE THREAD

**Issue by bayndrysf** [bounswe/bounswe2022group4#98]
It's decided to design a sequence diagram for "Delete a Comment". [issue#55](https://github.com/bounswe/bounswe2022group4/issues/55).

**Comment by bayndrysf** [comment]
Done. 
![issue98](https://user-images.githubusercontent.com/48126002/163584295-03452c15-e44f-451f-afd0-7f089a06a95e.png)

**Comment by BeratDamar** [comment]
I reviewed your design. I think that there is no problem. Therefore, I will close the issue. Thanks @bayndrysf
